# Generated by Django 4.1.6 on 2023-06-11 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('creator', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('category', models.CharField(max_length=300)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
